name: second_workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "This is the second workflow!"